schema_version = "1.0.0"

id = "blender_sfdi"
version = "0.1.0"

name = "blender_sfdi"
tagline = "TODO: Add"

maintainer = "Daniel Weston <psydw2@nottingham.ac.uk>"
website = "https://github.com/DannyWeston/blender-sfdi"
license = [
  "SPDX:GPL-2.0-or-later",
]

type = "add-on"
platforms = ["windows-x64"]
blender_version_min = "4.2.0"

wheels = [

]

[permissions]
network = "For doing y"
files = "For doing z"
clipboard = "For doing x"