schema_version = "1.0.0"

id = "sfdi"
version = "1.0.0"
name = "SFDI Addon"
tagline = "Extension for Fringe Projection and Photogrammetry"
maintainer = "Daniel Weston <psydw2@nottingham.ac.uk>"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "clipboard" (to read and/or write the system clipboard)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)

permissions = ["files", "network", "camera"]
website = "https://github.com/DannyWeston/blender-sfdi"

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0" # Optional

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]
# Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = ["windows-amd64"] # Other supported platforms: "macos-arm64", "linux-x86_64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl"
# ]

# Optional: build setting.
# https://docs.blender.org/manual/en/dev/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "/.git/"
#   "__pycache__/"
# ]